spring:
  datasource:
    username: root
    password: Moxtr@12
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

debug: true

logging:
  config: classpath:log4j2-spring.xml


mybatis:
  # 对应实体类的路径
  type-aliases-package: com.yechy.dailypic.entity
  # 指定myBatis的核心配置文件与Mapper映射文件,classpath:后面不需要加 /
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 开启驼峰命名规范自动映射
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl